### ISSUE TITLE
toolbox.Tools module issue

### ISSUE THREAD

**Issue by guamashton** [Jordan-Pierce/CoralNet-Toolbox#42]
After installing the toolbox, we get the following error:
ModuleNotFoundError: No module named 'toolbox.Tools'

We were able to resolve this by:
1) Downloading the full code
2) Copying the toolbox\Tools folder to C:\Users\[username]\AppData\Local\anaconda3\envs\[env name]\Lib\site-packages\toolbox folder

**Comment by Jordan-Pierce** [comment]
Interesting. I'll play around with a fresh install and see what this is about. Were you able to see GPU / rabbit?

**Comment by Jordan-Pierce** [comment]
Ah yes, okay I see. Will work on this.

**Comment by Jordan-Pierce** [comment]
@guamashton give it another go by first uninstalling, and then re-install (I would also delete the repo that you downloaded as well):

```python
# Uninstall
pip uninstall coralnet-toolbox

# Install
pip install "git+https://github.com/Jordan-Pierce/CoralNet-Toolbox.git"

# Run 
coralnet-toolbox

```
