### ISSUE TITLE
Feature request: ability to select and edit multiple annotations

### ISSUE THREAD

**Issue by guamashton** [Jordan-Pierce/CoralNet-Toolbox#55]
If it's not too difficult, I'd like to request a feature where we can select an area, highlight all the annotations within that area, and batch edit them.  This would be helpful when there's an area with some incorrect annotations, since it's difficult to select the desired annotation.

**Comment by Jordan-Pierce** [comment]
Hi @guamashton, agreed. This was something also suggested by another person, just haven't got around to doing it. I recently updated main (yesterday); if you update, you should see the ability to better select specific annotations even though they have significant overlap. 

I'll look at adding the ability to select multiple (left-click while holding Cntrl, or left-click and drag to select with a rectangle).

Notes to self:
- Add a list in the SelectTool for selected_annotations
- If Cntrl is held, each left click adds an annotation to the list 
- Each annotation needs to be set to active to show update graphic
- If the list is not empty, deselect the currently active label
- Once a label is selected, change all annotations in list to the currently active label
- If the list is not empty, and an event occurs in the window without Cntrl modifier, deselect all in the list, clear the list
- Create conditions to create a rectangle graphic if Cntrl is held and left-click is dragged
- Check if any annotations fall within rectangle (center_xy), add to the list, set active

**Comment by Jordan-Pierce** [comment]
This feature has been added. Cntrl + Left click to select multiple annotations (of any kind); hold Cntrl + Left click and drag a rectangle to select annotations. 

Multiple annotations can be changed to the same label, or deleted (not moved, or size change)

Multiple annotations can also be selected and then used with Image classification model
