### ISSUE TITLE
API tool crashing

### ISSUE THREAD

**Issue by JCHAREND** [Jordan-Pierce/CoralNet-Toolbox#6]
API tool says it completed the job, but when recording annotations for the completed job, it gives the attached error.
![image (1)](https://github.com/Jordan-Pierce/CoralNet-Toolbox/assets/92761012/486f46c7-8097-4746-8653-73c31585b865)

**Comment by Jordan-Pierce** [comment]
Hi @JCHAREND if you'll pull the latest version of the repository that problem **should** have been fixed in a [commit ](https://github.com/Jordan-Pierce/CoralNet-Toolbox/blob/main/Toolbox/Tools/API.py#L203)I made a few months ago. Apologies.
