### ISSUE TITLE
Annotations present after deleting a label

### ISSUE THREAD

**Issue by m-h-williams** [Jordan-Pierce/CoralNet-Toolbox#85]
### Environment Information

-   coralnet_toolbox version: 0.0.14
-   Python version: 3.10
-   Operating System: Windows 10 

### Description

Describe what you were trying to get done:

- I would like to delete a label and all associated annotations.

Tell us what happened, what went wrong, and what you expected to happen:

- When selecting a label in the label window and clicking `Delete Label` a window comes up to confirm my deletion and states that all associated annotations will be deleted as well. However, when I confirmed I wanted to delete the label, the annotations are still present.

**Comment by Jordan-Pierce** [comment]
@m-h-williams I'm not able to replicate the issue with version 0.0.14, but I did make modifications recently, so maybe something happened.

Can you confirm with your version that if you edit a label (change the color, for example) the application re-draws the scene with annotations with the new color? This is just a sanity check.

Regarding not deleting, can you post a screenshot of the application and if there's anything in the console? As if you delete a label, and it's not longer present in the project, I'm not sure what would happen if you click on an annotation of that deleted label.

**Comment by m-h-williams** [comment]
@Jordan-Pierce I may be updating the version incorrectly... What I have been doing is activating my conda environment which was created following your code `conda create --name coralnet10 python=3.10 -y`  then running `pip install coralnet-toolbox`

`(coralnet10) C:\Users\williamsm>pip install coralnet-toolbox`

I just redid this process and got the same result - deleted the label but annotations still exist. I also tried changing the color and that didn't work either.... strange. Must be something on my end.

For example I selected my sea star label (SS_ochre) and deleted it but the annotations still exist. You can see in the image below that the SS_ochre label is no longer in the label window, but the annotation is still there as seen in the confidence window. 
![image](https://github.com/user-attachments/assets/c17964cc-3816-452f-923a-f3d21e09d46f)

**Comment by Jordan-Pierce** [comment]
If you'll do a force update within your conda environment:

```bash
pip install coralnet-toolbox==0.0.15
```

And try again?

**Comment by m-h-williams** [comment]
That update fixed the ability to change the color of a label, meaning I can do that now as expected. But the annotations of a deleted label still exist like before.

**Comment by m-h-williams** [comment]
As a note, after doing the force update I saw that I was actually running coralnet 0.0.11, not 0.014
```
Installing collected packages: coralnet-toolbox
  Attempting uninstall: coralnet-toolbox
    Found existing installation: coralnet-toolbox 0.0.11
    Uninstalling coralnet-toolbox-0.0.11:
      Successfully uninstalled coralnet-toolbox-0.0.11
Successfully installed coralnet-toolbox-0.0.15
```

No, SS_ochre does not exist in other label short or long codes. For some background on my process:
- I uploaded images
- Uploaded an annotation file 
[2024_10_08_annotations.json](https://github.com/user-attachments/files/18202758/2024_10_08_annotations.json)
- Then uploaded a labelset 
[labelset_colors.json](https://github.com/user-attachments/files/18202762/labelset_colors.json)

**Comment by m-h-williams** [comment]
I just tried deleting another label that is in both the labelset and annotation file and that worked. The `SS_ochre' label is from a VIAME annotation file that I converted to a JSON annotation file for CoralNet-Toolbox. Perhaps something went wrong in that process

**Comment by Jordan-Pierce** [comment]
I don't see `SS_ochre` in the `labelset_colors.json` either.

**Comment by m-h-williams** [comment]
Correct, `SS_ochre` it is not in the labelset file, but is in the annotation file. My thought process was I wanted to upload annotations that I had done yesterday, but not all the labels had been annotated, so I also uploaded the complete labelset to view in the label window to continue annotating.

**Comment by m-h-williams** [comment]
@Jordan-Pierce it appears to be an issue with the annotations I converted from VIAME. So the good news is your toolbox is working as expected, re: deleting a labelset and changing the label color.

**Comment by Jordan-Pierce** [comment]
Lol, for once, it's stable haha

**Comment by m-h-williams** [comment]
Thanks for your help! Looks like I got some work to do on the VIAME conversion portion
